[package]
name = "xr-hotas"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
env_logger = "0.11.11"
glam = { version = "0.33.3", features = ["mint"] }
log = "0.4.33"
mint = "0.5.9"
openxr = { version = "0.21.1", default-features = false, features = ["mint", "linked"] }
signal-hook = "0.4.4"
